### ISSUE TITLE
sequelize deprecated - String based operators are now deprecated. 

### ISSUE THREAD

**Issue by drewwmercer** [drewwmercer/project-2#101]
when running `npm start` locally

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security

> read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:245:13

**Comment by maxzirps** [comment]
I would like to work on this

**Comment by drewwmercer** [comment]
Thank you @mensonones
