### ISSUE TITLE
Fix 'My Garage' link at top of pages to route to my-garage

### ISSUE THREAD

**Issue by drewwmercer** [drewwmercer/project-2#34]

**Comment by soub4i** [comment]
I think this issue is not occur

**Comment by drewwmercer** [comment]
@AbderrahimSoubaiElidrissi I think you're correct, the issue is 2 years old and was likely already resolved. Marking as invalid and closed.

**Comment by drewwmercer** [comment]
@soubai, this was an outdated issue and not marked for hacktoberfest, it
has been closed out as it was resolved previously. Apologies for the
confusion.
