### ISSUE TITLE
Add validation to new-bike miles field before allowing Add Bike

### ISSUE THREAD

**Issue by drewwmercer** [drewwmercer/project-2#83]
Miles should only take in an integer (positive whole numbers)

**Comment by soub4i** [comment]
I'm on this

**Comment by drewwmercer** [comment]
@AbderrahimSoubaiElidrissi this is still allowing form submission with a letter in the Miles field

**Comment by bofalke** [comment]
I could give it a try (:

**Comment by soub4i** [comment]
@drewwmercer You mean in the form ?

**Comment by drewwmercer** [comment]
@AbderrahimSoubaiElidrissi  when "t miles" is pasted in every field, the form accepts it.
